# Deployment Target
platform :ios, '11.0'
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

# Add pods as frameworks so we could add obj-c and swift 3.0 pods
use_frameworks!

target 'APPropertyWrappers_Example' do
    pod 'APPropertyWrappers/RxSwift', :path => '../'
    
    target 'APPropertyWrappers_Tests' do
      inherit! :search_paths
      
      pod 'Quick'
      pod 'Nimble'
      pod 'Nimble-Snapshots'
    end
end

post_install do |installer|
    # Add podInstall.command and podUpdate.command shell scripts to Pods project
    pods_project = installer.pods_project
    pods_project.new_file "../Scripts/Cocoapods/podInstall.command"
    pods_project.new_file "../Scripts/Cocoapods/podUpdate.command"
    
    # Silence deployment target warnings
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        config.build_settings.delete 'ARCHS'
      end
    end
end
